### ISSUE TITLE
update.yml fails

### ISSUE THREAD

**Issue by alexeystalker** [ObsidianPublisher/actions#2]
Hello. There is an error while performing Unzip Release step in "Get latest release from template" workflow. This is the error I've got:

```
Run unzip release.zip
  unzip release.zip
  rm release.zip
  shell: /usr/bin/bash -e {0}
Archive:  release.zip
replace overrides/hooks/on_page_markdown.py? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Error: Process completed with exit code 1.
```

**Comment by Mara-Li** [comment]
(I hate bash)
I forgot to set something. Sorry for that! Will fix that asap.

**Comment by Mara-Li** [comment]
Fixed, you should wait some times before retry

**Comment by alexeystalker** [comment]
Ok, I'll test later, thanks for quick response!
