### ISSUE TITLE
Auto update template will overwrite `overrides/partials/comments.html`

### ISSUE THREAD

**Issue by h4rvey-g** [ObsidianPublisher/actions#4]
Auto updating template will overwrite `overrides/partials/comments.html` to the default settings, causing error in comments.

**Comment by Mara-Li** [comment]
You can exclude file using "EXCLUDED_FILES" inputs

**Comment by yshalsager** [comment]
@Lisandra-dev EXCLUDED-FILES should be set in .env, right? Or it must be set manually through Action input? I have it [like this in my repo](https://github.com/yshalsager/digital-garden/blob/main/.github/.env#L2) and still [get files to be overridden](https://github.com/yshalsager/digital-garden/commit/3e8091ee2845724c9ce7ef72f53266ede41c0afb) by template update.

**Comment by Mara-Li** [comment]
The exclude must be in the actions!
See here: https://github.com/ObsidianPublisher/actions?tab=readme-ov-file#update-updateyml

**Comment by yshalsager** [comment]
> The exclude must be in the actions! See here: [ObsidianPublisher/actions?tab=readme-ov-file#update-updateyml](https://github.com/ObsidianPublisher/actions?tab=readme-ov-file#update-updateyml)

Can't you make it read from env file? I find it more convenient for automatic update, otherwise I have to disable automatic update and update manually while providing excluded files list.

**Comment by Mara-Li** [comment]
It's more logic and convenient that way. Just update your github action. You can also edit it to restore the original file, if you don't want to use the option (for... I don't know?)
