### ISSUE TITLE
[BUG]: Clean unused images throws errors caused by missing packages

### ISSUE THREAD

**Issue by nickynicolson** [ObsidianPublisher/actions#9]
### Conditions

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue doesn't concern the Template or the Obsidian Plugin. If you need, open a [issue](https://github.com/ObsidianPublisher/obsidian-github-publisher/issue) on the relative repository.

### Workflow

maintenance.yml: Repository maintenance

### workflow logs

https://github.com/nickynicolson/bison/actions/runs/6768713225/job/18393671453

### Error

```bash session
python package mermaid2 is missing, causing an error in "Clean unused images"
```

### Workflow configuration

As generated from the template https://github.com/ObsidianPublisher/template-gh-pages

**Comment by Mara-Li** [comment]
After checking your mkdocs, you don't need to add mermaid2 in your mkdocs, as they are directly handled by Material : https://squidfunk.github.io/mkdocs-material/reference/diagrams/#diagrams

Adjust your mkdocs.yml and rerun the actions

**Comment by nickynicolson** [comment]
I dont understand this - the main deploy works ok (https://github.com/ObsidianPublisher/actions/blob/main/.github/workflows/deploy.yml), but an error is thrown in this scheduled repository maintenance action (https://github.com/ObsidianPublisher/actions/blob/main/.github/workflows/maintenance.yml) so surely there must be some difference in the setup of the environments on which these two actions run? (Rather than a change required in my mkdocs.yml)

**Comment by Mara-Li** [comment]
Yeah, the main deploy use the whole environment, aka all plugins you set in your mkdocs.yml. The maintenance only use a little environment based on material Mkdocs. Normally, it shoulds ignore any plugins as I just use Mkdocs to parse the file. 
I need to test when I have the time.

**Comment by Mara-Li** [comment]
Okay, I know the culprit : The yaml parser.
Mermaid2 and mkdocs have nothing to do here

**Comment by Mara-Li** [comment]
Fixed in https://github.com/ObsidianPublisher/template-main/releases/tag/3.0.3

**Comment by nickynicolson** [comment]
Tried re-running following workflow release noted in previous comment. It now throws a similar error (missing package) on "materialx" - https://github.com/nickynicolson/bison/actions/runs/6774033407/job/18410216600

**Comment by Mara-Li** [comment]
Did you update the `clean_unused_image.py` ?
